<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "article".
 *
 * @property integer $id
 * @property string $name
 * @property string $intro
 * @property integer $article_category_id
 * @property integer $sort
 * @property integer $create_time
 * @property integer $status
 */
class Article extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'article';
    }
    public function getarticlecategory(){
        return $this->hasOne(ArticleCategory::className(),['id'=>'article_category_id']);
    }
    public function getarticledetail(){
        return $this->hasOne(ArticleDetail::className(),['article_id'=>'id']);
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name','intro'], 'required'],
            [['intro'], 'string'],
            [['article_category_id', 'sort', 'create_time', 'status'], 'integer'],
            [['name'], 'string', 'max' => 50],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => '名称',
            'intro' => '简介',
            'article_category_id' => '文章分类id',
            'sort' => '排序',
            'create_time' => '创建时间',
            'status' => '状态',
            'content' => '详情',
        ];
    }
    public function beforeSave($insert)
    {
        if($insert){
            $this->create_time=time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


}
